version: "3"
services:
  flask:
    container_name: flask
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "80:443"
      - "443:443"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=application.py
      - FLASK_DEBUG=0
    command: flask run --host=0.0.0.0 --port 443
