version: "3.8"
services:
  flask:
    container_name: WeddingSite
    build:
      context: ./flask
      dockerfile: Dfile
    ports:
      - "80:443"
      - "443:443"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=application.py
      - FLASK_DEBUG=0
      - EMAIL=$EMAIL
      - PASSWRD=$PASSWRD
    command: flask run --host=0.0.0.0 --port 443
